"""add search_vector

Revision ID: 5e90a75d37d7
Revises: 768cffc870d5
Create Date: 2026-03-05 02:38:31.592205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e90a75d37d7'
down_revision: Union[str, Sequence[str], None] = '768cffc870d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_sections_search_vector', 'sections', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sections_search_vector', table_name='sections', postgresql_using='gin')
    op.drop_column('sections', 'search_vector')
    # ### end Alembic commands ###
